[2023-12-13T16:34:40.145+0000] {processor.py:157} INFO - Started process (PID=2635) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:34:40.146+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:34:40.148+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:34:40.148+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:34:40.156+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:34:40.165+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.024 seconds
[2023-12-13T16:34:54.427+0000] {processor.py:157} INFO - Started process (PID=2647) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:34:54.438+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:34:54.452+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:34:54.452+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:34:54.464+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:34:54.480+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.059 seconds
[2023-12-13T16:35:25.002+0000] {processor.py:157} INFO - Started process (PID=2669) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:35:25.004+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:35:25.008+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:35:25.007+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:35:25.016+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:35:25.028+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.031 seconds
[2023-12-13T16:35:55.515+0000] {processor.py:157} INFO - Started process (PID=2691) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:35:55.517+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:35:55.524+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:35:55.523+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:35:55.534+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:35:55.548+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.041 seconds
[2023-12-13T16:36:25.945+0000] {processor.py:157} INFO - Started process (PID=2713) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:36:25.948+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:36:25.956+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:36:25.955+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:36:25.985+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:36:26.007+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.070 seconds
[2023-12-13T16:36:56.395+0000] {processor.py:157} INFO - Started process (PID=2735) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:36:56.399+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:36:56.406+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:36:56.405+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:36:56.439+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:36:56.461+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.075 seconds
[2023-12-13T16:37:26.824+0000] {processor.py:157} INFO - Started process (PID=2757) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:37:26.828+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:37:26.835+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:37:26.834+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:37:26.845+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:37:26.861+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.063 seconds
[2023-12-13T16:37:46.204+0000] {processor.py:157} INFO - Started process (PID=2772) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:37:46.207+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:37:46.211+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:37:46.211+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:37:46.218+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:37:46.217+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 5, in <module>
    from airflow.operators.python.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.python.PythonOperator'; 'airflow.operators.python' is not a package
[2023-12-13T16:37:46.219+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:37:46.245+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.046 seconds
[2023-12-13T16:37:49.255+0000] {processor.py:157} INFO - Started process (PID=2777) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:37:49.257+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:37:49.262+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:37:49.261+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:37:49.270+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:37:49.269+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 5, in <module>
    from airflow.operators.python.PythonOperator import PythonOperator
ModuleNotFoundError: No module named 'airflow.operators.python.PythonOperator'; 'airflow.operators.python' is not a package
[2023-12-13T16:37:49.271+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:37:49.293+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.043 seconds
[2023-12-13T16:38:03.562+0000] {processor.py:157} INFO - Started process (PID=2789) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:38:03.564+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:38:03.569+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:38:03.569+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:38:03.577+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:38:03.595+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.046 seconds
[2023-12-13T16:38:34.009+0000] {processor.py:157} INFO - Started process (PID=2811) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:38:34.012+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:38:34.017+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:38:34.016+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:38:34.023+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:38:34.040+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.040 seconds
[2023-12-13T16:39:04.502+0000] {processor.py:157} INFO - Started process (PID=2833) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:39:04.505+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:39:04.511+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:39:04.510+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:39:04.517+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:39:04.535+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.043 seconds
[2023-12-13T16:39:34.903+0000] {processor.py:157} INFO - Started process (PID=2855) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:39:34.906+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:39:34.912+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:39:34.911+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:39:34.919+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:39:34.942+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.055 seconds
[2023-12-13T16:40:05.521+0000] {processor.py:157} INFO - Started process (PID=2877) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:40:05.523+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:40:05.529+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:40:05.528+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:40:05.537+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:40:05.559+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.047 seconds
[2023-12-13T16:40:10.566+0000] {processor.py:157} INFO - Started process (PID=2882) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:40:10.568+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:40:10.573+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:40:10.572+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:40:10.579+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:40:10.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.038 seconds
[2023-12-13T16:40:41.112+0000] {processor.py:157} INFO - Started process (PID=2904) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:40:41.117+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:40:41.132+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:40:41.131+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:40:41.141+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:40:41.161+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.062 seconds
[2023-12-13T16:41:11.714+0000] {processor.py:157} INFO - Started process (PID=2926) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:41:11.719+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:41:11.735+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:41:11.733+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:41:11.740+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:41:11.758+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.065 seconds
[2023-12-13T16:41:14.972+0000] {processor.py:157} INFO - Started process (PID=2941) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:41:14.974+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:41:14.977+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:41:14.977+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:41:16.091+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:41:16.087+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:41:16.096+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:41:16.134+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 1.167 seconds
[2023-12-13T16:41:46.432+0000] {processor.py:157} INFO - Started process (PID=2963) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:41:46.435+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:41:46.439+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:41:46.439+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:41:47.582+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:41:47.579+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:41:47.584+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:41:47.607+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 1.182 seconds
[2023-12-13T16:42:17.970+0000] {processor.py:157} INFO - Started process (PID=2985) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:42:17.973+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:42:17.978+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:42:17.977+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:42:19.123+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:42:19.120+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:42:19.125+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:42:19.143+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 1.180 seconds
[2023-12-13T16:42:49.551+0000] {processor.py:157} INFO - Started process (PID=3007) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:42:49.553+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:42:49.556+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:42:49.556+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:42:50.605+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:42:50.601+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:42:50.609+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:42:50.639+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 1.096 seconds
[2023-12-13T16:43:20.964+0000] {processor.py:157} INFO - Started process (PID=3028) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:43:20.966+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:43:20.970+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:43:20.970+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:43:21.908+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:43:21.903+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:43:21.912+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:43:21.949+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.991 seconds
[2023-12-13T16:43:52.391+0000] {processor.py:157} INFO - Started process (PID=3057) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:43:52.393+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:43:52.397+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:43:52.396+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:43:53.330+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:43:53.326+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:43:53.334+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:43:53.372+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.990 seconds
[2023-12-13T16:44:23.821+0000] {processor.py:157} INFO - Started process (PID=3078) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:44:23.823+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:44:23.827+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:44:23.827+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:44:24.693+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:44:24.689+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:44:24.696+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:44:24.740+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.926 seconds
[2023-12-13T16:44:55.286+0000] {processor.py:157} INFO - Started process (PID=3100) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:44:55.288+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:44:55.292+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:44:55.292+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:44:56.451+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:44:56.444+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:44:56.456+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:44:56.517+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 1.237 seconds
[2023-12-13T16:45:26.792+0000] {processor.py:157} INFO - Started process (PID=3121) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:45:26.795+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:45:26.798+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:45:26.797+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:45:27.944+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:45:27.940+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:45:27.948+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:45:27.981+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 1.194 seconds
[2023-12-13T16:45:58.426+0000] {processor.py:157} INFO - Started process (PID=3143) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:45:58.429+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:45:58.435+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:45:58.434+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:45:59.456+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:45:59.452+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:45:59.458+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:45:59.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 1.078 seconds
[2023-12-13T16:46:29.847+0000] {processor.py:157} INFO - Started process (PID=3165) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:46:29.852+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:46:29.857+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:46:29.857+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:46:30.877+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:46:30.873+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:46:30.879+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:46:30.910+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 1.072 seconds
[2023-12-13T16:47:01.327+0000] {processor.py:157} INFO - Started process (PID=3187) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:47:01.330+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:47:01.336+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:47:01.336+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:47:02.421+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:47:02.415+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:47:02.426+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:47:02.486+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 1.165 seconds
[2023-12-13T16:47:32.815+0000] {processor.py:157} INFO - Started process (PID=3209) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:47:32.820+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:47:32.828+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:47:32.827+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:47:33.769+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:47:33.763+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 25, in <module>
    rest_api_call()
  File "/opt/airflow/dags/restapi.py", line 20, in rest_api_call
    with open(json_file_path,'a+') as datafile:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.json'
[2023-12-13T16:47:33.774+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:47:33.820+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 1.027 seconds
[2023-12-13T16:47:42.910+0000] {processor.py:157} INFO - Started process (PID=3214) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:47:42.912+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:47:42.915+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:47:42.915+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:47:42.924+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:47:42.938+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.033 seconds
[2023-12-13T16:48:04.402+0000] {processor.py:157} INFO - Started process (PID=3237) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:48:04.405+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:48:04.411+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:48:04.411+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:48:04.422+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:48:04.420+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 45, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:48:04.422+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:48:04.447+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.066 seconds
[2023-12-13T16:48:34.769+0000] {processor.py:157} INFO - Started process (PID=3259) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:48:34.771+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:48:34.777+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:48:34.776+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:48:34.784+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:48:34.782+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 45, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:48:34.784+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:48:34.828+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.066 seconds
[2023-12-13T16:48:54.019+0000] {processor.py:157} INFO - Started process (PID=3281) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:48:54.021+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:48:54.026+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:48:54.026+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:48:54.036+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:48:54.035+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:48:54.037+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:48:54.056+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.044 seconds
[2023-12-13T16:48:55.029+0000] {processor.py:157} INFO - Started process (PID=3286) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:48:55.030+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:48:55.033+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:48:55.033+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:48:55.040+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:48:55.039+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:48:55.040+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:48:55.056+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.031 seconds
[2023-12-13T16:49:18.355+0000] {processor.py:157} INFO - Started process (PID=3291) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:49:18.357+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:49:18.362+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:49:18.362+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:49:18.374+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:49:18.373+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:49:18.374+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:49:18.394+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.064 seconds
[2023-12-13T16:49:48.746+0000] {processor.py:157} INFO - Started process (PID=3313) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:49:48.754+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:49:48.773+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:49:48.772+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:49:48.786+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:49:48.781+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:49:48.786+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:49:48.807+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.069 seconds
[2023-12-13T16:50:19.357+0000] {processor.py:157} INFO - Started process (PID=3335) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:50:19.360+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:50:19.367+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:50:19.366+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:50:19.374+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:50:19.372+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:50:19.374+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:50:19.393+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.062 seconds
[2023-12-13T16:50:49.738+0000] {processor.py:157} INFO - Started process (PID=3357) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:50:49.739+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:50:49.744+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:50:49.744+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:50:49.751+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:50:49.750+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:50:49.752+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:50:49.772+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.041 seconds
[2023-12-13T16:51:20.367+0000] {processor.py:157} INFO - Started process (PID=3379) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:51:20.368+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:51:20.371+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:51:20.371+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:51:20.376+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:51:20.375+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:51:20.376+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:51:20.399+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.037 seconds
[2023-12-13T16:51:50.739+0000] {processor.py:157} INFO - Started process (PID=3401) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:51:50.741+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:51:50.745+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:51:50.745+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:51:50.751+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:51:50.749+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:51:50.751+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:51:50.779+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.044 seconds
[2023-12-13T16:52:21.342+0000] {processor.py:157} INFO - Started process (PID=3423) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:52:21.345+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:52:21.351+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:52:21.350+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:52:21.357+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:52:21.356+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:52:21.358+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:52:21.374+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.041 seconds
[2023-12-13T16:52:51.702+0000] {processor.py:157} INFO - Started process (PID=3445) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:52:51.703+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:52:51.706+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:52:51.706+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:52:51.711+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:52:51.710+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:52:51.712+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:52:51.728+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.028 seconds
[2023-12-13T16:53:22.092+0000] {processor.py:157} INFO - Started process (PID=3467) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:53:22.097+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:53:22.107+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:53:22.106+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:53:22.124+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:53:22.122+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:53:22.124+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:53:22.146+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.075 seconds
[2023-12-13T16:53:52.555+0000] {processor.py:157} INFO - Started process (PID=3489) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:53:52.558+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:53:52.564+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:53:52.564+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:53:52.572+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:53:52.570+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:53:52.572+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:53:52.596+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.049 seconds
[2023-12-13T16:53:54.648+0000] {processor.py:157} INFO - Started process (PID=3511) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:53:54.649+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:53:54.651+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:53:54.651+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:53:54.656+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:53:54.656+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 33, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:53:54.657+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:53:54.671+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.026 seconds
[2023-12-13T16:54:08.873+0000] {processor.py:157} INFO - Started process (PID=3516) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:54:08.875+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:54:08.880+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:54:08.880+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:54:08.890+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:54:08.888+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 48, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:54:08.890+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:54:08.913+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.048 seconds
[2023-12-13T16:54:10.897+0000] {processor.py:157} INFO - Started process (PID=3521) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:54:10.898+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:54:10.900+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:54:10.900+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:54:10.907+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:54:10.906+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 47, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 34, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:54:10.908+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:54:10.929+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.037 seconds
[2023-12-13T16:54:16.019+0000] {processor.py:157} INFO - Started process (PID=3526) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:54:16.021+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:54:16.025+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:54:16.024+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:54:16.033+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:54:16.032+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 48, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:54:16.034+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:54:16.051+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.037 seconds
[2023-12-13T16:54:46.455+0000] {processor.py:157} INFO - Started process (PID=3548) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:54:46.457+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:54:46.462+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:54:46.461+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:54:46.472+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:54:46.471+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 48, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:54:46.473+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:54:46.497+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.048 seconds
[2023-12-13T16:55:16.818+0000] {processor.py:157} INFO - Started process (PID=3570) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:55:16.820+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:55:16.824+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:55:16.824+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:55:16.829+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:55:16.827+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 48, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:55:16.829+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:55:16.857+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.044 seconds
[2023-12-13T16:55:36.070+0000] {processor.py:157} INFO - Started process (PID=3592) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:55:36.072+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:55:36.075+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:55:36.075+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:55:36.086+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:55:36.085+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 48, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:55:36.086+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:55:36.106+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.042 seconds
[2023-12-13T16:56:06.511+0000] {processor.py:157} INFO - Started process (PID=3614) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:56:06.514+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:56:06.520+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:56:06.519+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:56:06.526+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:56:06.525+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 48, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:56:06.527+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:56:06.545+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.042 seconds
[2023-12-13T16:56:36.867+0000] {processor.py:157} INFO - Started process (PID=3636) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:56:36.868+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:56:36.872+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:56:36.871+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:56:36.877+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:56:36.876+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 48, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:56:36.878+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:56:36.900+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.038 seconds
[2023-12-13T16:56:53.152+0000] {processor.py:157} INFO - Started process (PID=3641) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:56:53.154+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:56:53.160+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:56:53.160+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:56:53.171+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:56:53.169+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:56:53.171+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:56:53.194+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.066 seconds
[2023-12-13T16:57:23.508+0000] {processor.py:157} INFO - Started process (PID=3663) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:57:23.510+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:57:23.530+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:57:23.529+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:57:23.543+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:57:23.540+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:57:23.543+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:57:23.566+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.064 seconds
[2023-12-13T16:57:53.936+0000] {processor.py:157} INFO - Started process (PID=3691) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:57:53.940+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:57:53.947+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:57:53.946+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:57:53.962+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:57:53.958+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:57:53.963+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:57:54.016+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.088 seconds
[2023-12-13T16:58:24.454+0000] {processor.py:157} INFO - Started process (PID=3715) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:58:24.457+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:58:24.464+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:58:24.463+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:58:24.470+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:58:24.468+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:58:24.470+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:58:24.491+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.045 seconds
[2023-12-13T16:58:54.837+0000] {processor.py:157} INFO - Started process (PID=3737) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:58:54.840+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:58:54.846+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:58:54.845+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:58:54.854+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:58:54.852+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:58:54.854+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:58:54.878+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.050 seconds
[2023-12-13T16:59:25.706+0000] {processor.py:157} INFO - Started process (PID=3760) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:59:25.709+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:59:25.714+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:59:25.713+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:59:25.727+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:59:25.719+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:59:25.728+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:59:25.774+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.075 seconds
[2023-12-13T16:59:56.250+0000] {processor.py:157} INFO - Started process (PID=3782) to work on /opt/airflow/dags/restapi.py
[2023-12-13T16:59:56.251+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T16:59:56.256+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:59:56.256+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T16:59:56.263+0000] {logging_mixin.py:154} INFO - [2023-12-13T16:59:56.261+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T16:59:56.263+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T16:59:56.308+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.065 seconds
[2023-12-13T17:00:26.681+0000] {processor.py:157} INFO - Started process (PID=3804) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:00:26.686+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:00:26.707+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:00:26.706+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:00:26.715+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:00:26.713+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:00:26.716+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:00:26.741+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.067 seconds
[2023-12-13T17:00:57.118+0000] {processor.py:157} INFO - Started process (PID=3826) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:00:57.120+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:00:57.139+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:00:57.137+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:00:57.156+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:00:57.153+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:00:57.156+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:00:57.184+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.073 seconds
[2023-12-13T17:01:27.547+0000] {processor.py:157} INFO - Started process (PID=3848) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:01:27.549+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:01:27.555+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:01:27.555+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:01:27.570+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:01:27.561+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:01:27.572+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:01:27.627+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.087 seconds
[2023-12-13T17:01:58.065+0000] {processor.py:157} INFO - Started process (PID=3870) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:01:58.070+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:01:58.084+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:01:58.083+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:01:58.105+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:01:58.101+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:01:58.105+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:01:58.130+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.097 seconds
[2023-12-13T17:02:28.485+0000] {processor.py:157} INFO - Started process (PID=3892) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:02:28.488+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:02:28.493+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:02:28.492+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:02:28.500+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:02:28.498+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:02:28.500+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:02:28.518+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.040 seconds
[2023-12-13T17:02:59.168+0000] {processor.py:157} INFO - Started process (PID=3914) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:02:59.182+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:02:59.192+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:02:59.191+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:02:59.202+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:02:59.200+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:02:59.203+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:02:59.287+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.140 seconds
[2023-12-13T17:03:30.070+0000] {processor.py:157} INFO - Started process (PID=3935) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:03:30.072+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:03:30.092+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:03:30.091+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:03:30.098+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:03:30.097+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:03:30.099+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:03:30.123+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.060 seconds
[2023-12-13T17:04:00.502+0000] {processor.py:157} INFO - Started process (PID=3957) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:04:00.507+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:04:00.518+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:04:00.517+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:04:00.525+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:04:00.523+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:04:00.526+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:04:00.550+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.072 seconds
[2023-12-13T17:04:30.901+0000] {processor.py:157} INFO - Started process (PID=3979) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:04:30.904+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:04:30.911+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:04:30.910+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:04:30.920+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:04:30.917+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:04:30.921+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:04:30.970+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.078 seconds
[2023-12-13T17:05:01.918+0000] {processor.py:157} INFO - Started process (PID=4001) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:05:01.921+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:05:01.927+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:05:01.927+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:05:01.933+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:05:01.932+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:05:01.934+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:05:01.957+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.053 seconds
[2023-12-13T17:26:13.588+0000] {processor.py:157} INFO - Started process (PID=4016) to work on /opt/airflow/dags/restapi.py
[2023-12-13T17:26:13.591+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T17:26:13.611+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:26:13.610+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T17:26:13.620+0000] {logging_mixin.py:154} INFO - [2023-12-13T17:26:13.618+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T17:26:13.621+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T17:26:13.668+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.088 seconds
[2023-12-13T18:15:55.623+0000] {processor.py:157} INFO - Started process (PID=4042) to work on /opt/airflow/dags/restapi.py
[2023-12-13T18:15:55.628+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T18:15:55.639+0000] {logging_mixin.py:154} INFO - [2023-12-13T18:15:55.638+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T18:15:55.666+0000] {logging_mixin.py:154} INFO - [2023-12-13T18:15:55.656+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T18:15:55.668+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T18:15:55.753+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.160 seconds
[2023-12-13T19:22:17.717+0000] {processor.py:157} INFO - Started process (PID=4064) to work on /opt/airflow/dags/restapi.py
[2023-12-13T19:22:17.732+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T19:22:17.747+0000] {logging_mixin.py:154} INFO - [2023-12-13T19:22:17.745+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T19:22:17.775+0000] {logging_mixin.py:154} INFO - [2023-12-13T19:22:17.770+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T19:22:17.777+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T19:22:17.846+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.142 seconds
[2023-12-13T20:39:52.580+0000] {processor.py:157} INFO - Started process (PID=4088) to work on /opt/airflow/dags/restapi.py
[2023-12-13T20:39:52.582+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T20:39:52.588+0000] {logging_mixin.py:154} INFO - [2023-12-13T20:39:52.587+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T20:39:52.606+0000] {logging_mixin.py:154} INFO - [2023-12-13T20:39:52.598+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T20:39:52.608+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T20:39:52.655+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.093 seconds
[2023-12-13T22:16:55.367+0000] {processor.py:157} INFO - Started process (PID=4110) to work on /opt/airflow/dags/restapi.py
[2023-12-13T22:16:55.370+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T22:16:55.377+0000] {logging_mixin.py:154} INFO - [2023-12-13T22:16:55.376+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T22:16:55.395+0000] {logging_mixin.py:154} INFO - [2023-12-13T22:16:55.393+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T22:16:55.397+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T22:16:55.446+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.092 seconds
[2023-12-13T23:43:20.479+0000] {processor.py:157} INFO - Started process (PID=4132) to work on /opt/airflow/dags/restapi.py
[2023-12-13T23:43:20.482+0000] {processor.py:829} INFO - Processing file /opt/airflow/dags/restapi.py for tasks to queue
[2023-12-13T23:43:20.487+0000] {logging_mixin.py:154} INFO - [2023-12-13T23:43:20.487+0000] {dagbag.py:536} INFO - Filling up the DagBag from /opt/airflow/dags/restapi.py
[2023-12-13T23:43:20.494+0000] {logging_mixin.py:154} INFO - [2023-12-13T23:43:20.492+0000] {dagbag.py:346} ERROR - Failed to import: /opt/airflow/dags/restapi.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/dagbag.py", line 342, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/restapi.py", line 46, in <module>
    json_to_csv()
  File "/opt/airflow/dags/restapi.py", line 35, in json_to_csv
    with open(csv_file_path,'w') as data_file:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/sarthakgarg/desktop/airflow_projects/raw_data/test.csv'
[2023-12-13T23:43:20.494+0000] {processor.py:841} WARNING - No viable dags retrieved from /opt/airflow/dags/restapi.py
[2023-12-13T23:43:20.521+0000] {processor.py:179} INFO - Processing /opt/airflow/dags/restapi.py took 0.070 seconds
