[2023-12-14T08:39:10.317+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: restapi-pipeline.copy_into_csv_table scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2023-12-14T08:39:10.323+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: restapi-pipeline.copy_into_csv_table scheduled__2023-12-13T00:00:00+00:00 [queued]>
[2023-12-14T08:39:10.323+0000] {taskinstance.py:1361} INFO - Starting attempt 3 of 3
[2023-12-14T08:39:10.330+0000] {taskinstance.py:1382} INFO - Executing <Task(SnowflakeOperator): copy_into_csv_table> on 2023-12-13 00:00:00+00:00
[2023-12-14T08:39:10.334+0000] {standard_task_runner.py:57} INFO - Started process 347 to run task
[2023-12-14T08:39:10.340+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'restapi-pipeline', 'copy_into_csv_table', 'scheduled__2023-12-13T00:00:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/restapi.py', '--cfg-path', '/tmp/tmpmnl3ydyh']
[2023-12-14T08:39:10.343+0000] {standard_task_runner.py:85} INFO - Job 115: Subtask copy_into_csv_table
[2023-12-14T08:39:10.374+0000] {task_command.py:416} INFO - Running <TaskInstance: restapi-pipeline.copy_into_csv_table scheduled__2023-12-13T00:00:00+00:00 [running]> on host b5f695589db2
[2023-12-14T08:39:10.415+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='sarthak' AIRFLOW_CTX_DAG_ID='restapi-pipeline' AIRFLOW_CTX_TASK_ID='copy_into_csv_table' AIRFLOW_CTX_EXECUTION_DATE='2023-12-13T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-12-13T00:00:00+00:00'
[2023-12-14T08:39:10.417+0000] {sql.py:274} INFO - Executing: COPY INTO organizations (Index,Organization_Id,Name,Website,Country,Description,Founded,Industry,Number_of_employees)
FROM @my_s3_stage
FILE_FORMAT = (FORMAT_NAME = my_csv_format)
ON_ERROR=CONTINUE 
[2023-12-14T08:39:10.423+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-12-14T08:39:10.429+0000] {base.py:73} INFO - Using connection ID 'snowflake_default' for task execution.
[2023-12-14T08:39:10.429+0000] {connection.py:334} INFO - Snowflake Connector for Python Version: 3.3.1, Python Version: 3.8.18, Platform: Linux-6.5.11-linuxkit-aarch64-with-glibc2.17
[2023-12-14T08:39:10.431+0000] {connection.py:1103} INFO - This connection is in OCSP Fail Open Mode. TLS Certificates would be checked for validity and revocation status. Any other Certificate Revocation related exceptions or OCSP Responder failures would be disregarded in favor of connectivity.
[2023-12-14T08:39:10.431+0000] {connection.py:1121} INFO - Setting use_openssl_only mode to False
[2023-12-14T08:39:11.157+0000] {cursor.py:833} INFO - query: [ALTER SESSION SET autocommit=False]
[2023-12-14T08:39:11.299+0000] {cursor.py:846} INFO - query execution done
[2023-12-14T08:39:11.300+0000] {cursor.py:988} INFO - Number of results in first chunk: 1
[2023-12-14T08:39:11.300+0000] {sql.py:418} INFO - Running statement: COPY INTO organizations (Index,Organization_Id,Name,Website,Country,Description,Founded,Industry,Number_of_employees)
FROM @my_s3_stage
FILE_FORMAT = (FORMAT_NAME = my_csv_format)
ON_ERROR=CONTINUE, parameters: None
[2023-12-14T08:39:11.301+0000] {cursor.py:833} INFO - query: [COPY INTO organizations (Index,Organization_Id,Name,Website,Country,Description,...]
[2023-12-14T08:39:12.148+0000] {cursor.py:846} INFO - query execution done
[2023-12-14T08:39:12.154+0000] {connection.py:677} INFO - closed
[2023-12-14T08:39:12.218+0000] {connection.py:683} INFO - No async queries seem to be running, deleting session
[2023-12-14T08:39:12.293+0000] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/operators/sql.py", line 280, in execute
    output = hook.run(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/snowflake/hooks/snowflake.py", line 388, in run
    self._run_command(cur, sql_statement, parameters)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/providers/common/sql/hooks/sql.py", line 423, in _run_command
    cur.execute(sql_statement)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/cursor.py", line 937, in execute
    Error.errorhandler_wrapper(self.connection, self, error_class, errvalue)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 290, in errorhandler_wrapper
    handed_over = Error.hand_to_other_handler(
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 345, in hand_to_other_handler
    cursor.errorhandler(connection, cursor, error_class, error_value)
  File "/home/airflow/.local/lib/python3.8/site-packages/snowflake/connector/errors.py", line 221, in default_errorhandler
    raise error_class(
snowflake.connector.errors.ProgrammingError: 091003 (22000): 01b0faa7-3200-f6b5-0007-4442000180aa: Failure using stage area. Cause: [The AWS Access Key Id you provided is not valid.]
[2023-12-14T08:39:12.298+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=restapi-pipeline, task_id=copy_into_csv_table, execution_date=20231213T000000, start_date=20231214T083910, end_date=20231214T083912
[2023-12-14T08:39:12.305+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 115 for task copy_into_csv_table (091003 (22000): 01b0faa7-3200-f6b5-0007-4442000180aa: Failure using stage area. Cause: [The AWS Access Key Id you provided is not valid.]; 347)
[2023-12-14T08:39:12.345+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-12-14T08:39:12.355+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
